### ISSUE TITLE
Fix broken links on website

### ISSUE THREAD

**Issue by michaelboyles** [hawtio/website#18]
Please fix the numerous broken line on your website. It is currently basically unusable. Every page seems to lead me to at least one 404.

You can use https://www.brokenlinkcheck.com/ to crawl for broken links, of which there are currently over 100.

**Comment by jamesnetherton** [comment]
Here's a list of broken stuff:

https://gist.github.com/jamesnetherton/2e3ff534f2dd22223bdb1a6cd0414bac

**Comment by abkieling** [comment]
Thanks. I think we could update the remaining v1 pages before fixing the links. I think most of the broken links are in those pages.

**Comment by abkieling** [comment]
Fixed
