### ISSUE TITLE
How to accommodate external component README.md files?

### ISSUE THREAD

**Issue by tadayosi** [hawtio/website#3]
Investigate how to accommodate external component `README.md` files (eg. https://github.com/hawtio/hawtio-core/blob/master/README.md) into the website.

Can we just link it to each `README`?  Or should each component host a published site at `hawtio.github.io/hawtio-<component>`?

**Comment by abkieling** [comment]
I think we can just link to the repository URLs when required.

**Comment by tadayosi** [comment]
Just linking the READMEs is ok as a temporal solution, but ideally it's better for the official website to have the same level of detailed documentation as https://github.com/hawtio/hawtio-core. It's also ideal that the other components such as hawtio-jmx and hawtio-integration have the same level of documentation somewhere.

Maybe we can consolidate & maintain the detailed documentation on each component here and keep README for each component as simple as possible.
