### ISSUE TITLE
Non-obvious authentication switch for Spring Boot

### ISSUE THREAD

**Issue by cambromley** [hawtio/website#31]
If you're using application.yml or similar you need to do this:

```
hawtio:
      authenticationEnabled: "false"
```
If you miss the quotes around the word 'false' you will get weird exceptions from hawtio at startup about not being able to read a map as opposed to a string.

**Comment by abkieling** [comment]
Hi @cambromley . Did you add a space after the colon?

**Comment by prahaladhchandrahasan** [comment]
Hi @cambromley . I have tired to reproduce your issue and i couldn't do so :(. The program works fine if both double quotes, single quote and no quotes. I'm closing this issue for now, If you still face it please raise a new issue and we will look in to that.
