### ISSUE TITLE
Document configuration to enable tracing & debugging for Camel 3.x

### ISSUE THREAD

**Issue by jamesnetherton** [hawtio/website#32]
Follow up on https://github.com/hawtio/hawtio-integration/issues/97.

In Camel 3, some things that were enabled by default in Camel 2.x are now disabled.

It's not obvious that some extra config is required to enable debugging and tracing in Hawtio. We should document this for Camel standalone & Camel Spring Boot.

**Comment by arheom** [comment]
Any progress on this one? I am having same issue for debugging. Got the correct configs for tracing from the other issue, but could not find the debugging config. Any idea what do I need to change to have debugging shown?

Thanks!

**Comment by jamesnetherton** [comment]
It's not possible to configure debugging via Spring properties like tracing.

Here's the slightly sub-optimal solution to enable debugging:

https://github.com/hawtio/hawtio/blob/master/examples/springboot/src/main/java/io/hawt/example/spring/boot/SampleCamelRouter.java#L11-L12

I'll try to add some notes to the website when I get some time.
