### ISSUE TITLE
Version matrix information for dependencies and related components

### ISSUE THREAD

**Issue by tadayosi** [hawtio/website#45]
There should be a comprehensive version matrix in the docs on the supported versions of Java, Jakarata EE, runtimes (Quarkus and Spring Boot),  corresponding Hawtio Online/Operator, and OpenShift and Kubernetes.

Relates #42.

**Comment by tadayosi** [comment]
@jsolovjo Added https://github.com/hawtio/website/blob/main/modules/ROOT/pages/versions.adoc so you can maintain the page.

**Comment by jsolovjo** [comment]
Hi @tadayosi 
where can I find the versions of Jakarta, Quarkus, Spring Boot and Apache Camel we are going to support?

**Comment by tadayosi** [comment]
@jsolovjo Normally it's in pom.xml and for Java versions they are certified with the GitHub actions.

**Comment by jsolovjo** [comment]
As the PR #46 was merged, I believe we can close the ticket.
