### ISSUE TITLE
Update Get Started guide

### ISSUE THREAD

**Issue by tadayosi** [hawtio/website#5]

**Comment by abkieling** [comment]
I'm working on it.

**Comment by abkieling** [comment]
@tadayosi @astefanutti @jamesnetherton I updated the Get Started guide but need someone to review it. I found issues with the standalone versions of Hawtio and we'll need to fix them before releasing the new documentation.

**Comment by tadayosi** [comment]
@alexkieling Awesome work, thanks!  A bit of feedback follows:

- I introduced `gatsby-remark-autolink-headers` plugin so manual anchors like `<a id="jar"></a>` aren't necessary. You can just link the sections like you do on GitHub.
https://github.com/hawtio/hawtio.github.io/blob/develop/gatsby-config.js#L29

- We can drop support for older Karaf (lower than 4.x) and Jetty 8 for Hawtio v2. Jetty 9.x should be supported instead.

- I noticed there's the section "Using a git clone" but let's restate it as "Run with a Spring Boot application" or something like that. It's also good to link it at the top. We may also push it to the 1st or 2nd in order, as Spring Boot support is one of our strong selling points :wink:
