### ISSUE TITLE
Update Configuration guide

### ISSUE THREAD

**Issue by tadayosi** [hawtio/website#6]

**Comment by tadayosi** [comment]
Working on it.

**Comment by tadayosi** [comment]
@alexkieling @astefanutti @jamesnetherton I've just updated Configuration guide. Could you guys review this?
https://hawtio.github.io/website/docs/configuration/

**Comment by tadayosi** [comment]
Related tasks:
- hawtio/hawtio/issues/2475
- hawtio/hawtio/issues/2476
- hawtio/hawtio/issues/2477

**Comment by jamesnetherton** [comment]
Updates seem ok. Minor typo was introduced - 'credentails'.

**Comment by tadayosi** [comment]
@jamesnetherton Good catch. Thanks. Fixed typos.
